name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dushyantsharmma }}
          password: ${{ secrets.dckr_pat_PJMO1BML1i9o4XKL12EIEvmdMkQ }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.dushyantsharmma }}/nodejs-demo-app:latest .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.dushyantsharmma }}/nodejs-demo-app:latest
